version: "3"

services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag_standalone
    restart: unless-stopped
    environment:
      - SYMFONY__ENV__DATABASE_HOST=${DATABASE_HOST}
      - SYMFONY__ENV__DATABASE_PORT=${DATABASE_PORT}
      - SYMFONY__ENV__DATABASE_NAME=${DATABASE_NAME}
      - SYMFONY__ENV__DATABASE_USER=${DATABASE_USER}
      - SYMFONY__ENV__DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SYMFONY__ENV__DATABASE_DRIVER=${DATABASE_DRIVER}
      - SYMFONY__ENV__DATABASE_PATH=${DATABASE_PATH}
      - SYMFONY__ENV__DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - postgres
      - redis      
    volumes:
      - ./data:/var/www/wallabag/data
    ports:
      - "8080:80"
  postgres:
      image: postgres:11-alpine
      container_name: wallabag_postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - ./db-data:/var/lib/postgresql/data
      healthcheck:
          test: ["CMD-SHELL", "pg_isready -U wallabag -q || exit 1"]
          interval: 10s
          timeout: 3s
          retries: 3
  redis:
      image: redis:6-alpine
      container_name: wallabag_redis
      restart: unless-stopped
      healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 10s
          timeout: 3s
          retries: 3